### ISSUE TITLE
ResourceBundle._path is referenced before assignment

### ISSUE THREAD

**Issue by cart0iv** [felix-zenk/ResourceBundle#1]
First, many thanks for the ResourceBundle package.  I've been running 1.0.4 successfully for a while now.  Unfortunately having issues with 2.0.1.  When I execute the example in the read me using python, I encounter the following:

 "AttributeError: 'ResourceBundle' object has no attribute '_path'"

The line of code referenced is line 97 of __init__.py.  Immediately I was curious with how self._path was set.
 
 I may be completely off base as I am very new to python, but if I either comment out line 64 of __init__.py OR move line 65 (which seems to assign self._path) above line 64, I do get past the error.  
 
My guess is that I am still doing something wrong despite following the read me.   Thanks for your time.

**Comment by felix-zenk** [comment]
Thanks for pointing that out. This is kind of an obvious mistake by me and you're right: switching lines 64 and 65 fixes the problem completely. :)
The issue has now been fixed with version 2.0.2
